### PR TITLE
Merging UI/UX changes to present choice of policy format in policy creation workflow

### PR DESCRIPTION
**Pull request by jgeurten**
New UI/UX for policy creation. The option to create a single (legacy) policy format vs multiple policy format was removed from the settings page and placed on the Select a Policy Type page (page 1 of the New Policy creation workflow)

Default: Multiple Policy Format
- Exposes the base and supplemental panel

Selecting Single Policy Format
- hides the base and supplemental panel. Clicking Next > Template page 

image

### CODE REVIEW

**Comment by isbrahm** [comment]
According to John Nix, the EPA specifically requested that the single vs. multi policy format option should be in the policy creation flow and not in the settings.

**Review by isbrahm — APPROVED** [review]
This looks great! I made one wording change to call out Server. Could you also move the link to the docs under Multiple Policy Format instead of Supplemental Policies? It could say "Learn more about multiple policy format"

**Comment by jgeurten** [comment]
> This looks great! I made one wording change to call out Server. Could you also move the link to the docs under Multiple Policy Format instead of Supplemental Policies? It could say "Learn more about multiple policy format"

Nice change!

**Comment by jgeurten** [comment]
Added new commits to change the policy format default to be determined based on the previous time the page was loaded (good idea, @isbrahm). Changed the position of the hyperlink on the page to underneath the Multiple Policy Format text. Fixed a settings bug. Tested all changed.

**Pull request merged**
